name: test

on: [push]

jobs:
  lint_unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
    - name: yarn install
      run: yarn
    - name: lint
      run: yarn lint
    - name: unit test
      run: yarn test:unit

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        command: ['yarn test:uvu && yarn test:jest', 'yarn test:tape && yarn test:ava']

    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
    - name: yarn install --frozen-lockfile
      run: yarn
    - name: test section
      run: ${{ matrix.command }}
